FROM golang:{{ .version }} as builder 

WORKDIR /build

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o {{ .name }} ./cmd/{{ .name }}/main.go


FROM alpine:latest

RUN apk --no-cache add ca-certificates bash

WORKDIR /app

COPY --from=builder /build/{{ .name }} .

CMD ["./{{ .name }}"]
